@startuml
class Prosjekt{
    prosjektid : int
    prosjektnavn : varchar
    prosjektbeskrivelse: varchar
    sammerbeidsbedrift : integer
    qrcodeurl : varchar
}

class Bedrift{
    bedriftid : int
    bedriftnavn : varchar
    bedriftbeskrivelse : varchar
}

class Stemme{
    stemmeid : int
    prosjektid : int
    epost : varchar
    stemmeverdi : int
    stemmetidspunkt : timestamp
}

Bedrift "1" *-- "*" Prosjekt
Stemme "*" -- "1" Prosjekt
@enduml