@startuml

class Arrangement {
}

class Utstilling {
}

class Stemme {
}

class Bedrift{
}

class Studie{
}

Utstilling "many" -- "1" Studie : < Består av
Utstilling "many" -- "1" Bedrift : < Består av
Utstilling "many" --* "1" Arrangement : < Består av
Stemme "many" -- "1" Utstilling : < Består av

@enduml