@startuml

class Arrangement {
}

class Utstilling {
    Navn
}

class Stemme {
    Vekt
}

class Besøkende{
    ID
}

Besøkende -- Stemme : > stemmer

Arrangement *- Utstilling : Består av >

Stemme -- Utstilling : < Har

@enduml