@startuml

Bruker -left-> [Web]

[Controller] ..> [Beans]

[Controller] -right-> [Service]

[Controller] -up-> [Web]

[Repository] ..> [Beans]

[Repository] --> Database

[Service] ..> [Beans]

[Service] -right-> [Repository]

database "Database"{
}


note right of [Beans]
    Data fra databasen overføres som beans
end note

@enduml